//! Usage-aware job scheduler. A headless `ccsm --watch` daemon dispatches
//! Claude Code sessions into tmux, pauses them when account usage crosses a
//! threshold, and resumes them when the usage window resets. This module
//! defines the persisted job model (`Job`/`Schedule`), the on-disk store
//! (`store`), the command queue used by the TUI to talk to the daemon
//! (`command`), and the pure decision engine (`engine`).

use crate::config::PauseMode;
use serde::{Deserialize, Serialize};

pub mod command;
pub mod engine;
pub mod store;

#[cfg(test)]
mod tests;

/// Lifecycle state of a managed job.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum JobState {
    /// Waiting to be dispatched into tmux.
    #[default]
    Queued,
    /// Dispatch has been requested but the tmux session does not exist yet.
    Starting,
    /// The tmux session exists and claude is actively running.
    Running,
    /// A pause has been requested but not yet confirmed.
    Pausing,
    /// Paused; waiting for usage to fall or a scheduled resume time.
    Paused,
    /// A resume has been requested but not yet confirmed.
    Resuming,
    /// The tmux session ended without the job being explicitly stopped.
    Stopped,
    /// Blocked on something the daemon cannot resolve automatically.
    Blocked,
    /// Finished successfully; no further action will be taken.
    Done,
    /// Given up after exhausting restart attempts.
    Failed,
}

/// One recorded state transition in a job's history.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobEvent {
    /// Epoch ms when the transition happened.
    #[serde(default)]
    pub at_ms: i64,
    /// State transitioned from.
    #[serde(default)]
    pub from: JobState,
    /// State transitioned to.
    #[serde(default)]
    pub to: JobState,
    /// Human-readable reason for the transition.
    #[serde(default)]
    pub reason: String,
}

/// A single managed session job tracked by the scheduler.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Job {
    /// ccsm's own identifier for this job (a uuid v4), generated by the TUI.
    #[serde(default)]
    pub id: String,
    /// User-facing label; sanitized elsewhere into a tmux session name.
    #[serde(default)]
    pub name: String,
    /// Working directory. MUST be stored already canonicalized; see `canonical_cwd`.
    #[serde(default)]
    pub cwd: String,
    /// Initial prompt; may be empty for adopted jobs.
    #[serde(default)]
    pub prompt: String,
    /// Text pasted to continue after a pause. `None` means use `Config::continue_prompt`.
    #[serde(default)]
    pub continue_prompt: Option<String>,
    /// The underlying Claude Code session id, once known.
    #[serde(default)]
    pub claude_session_id: Option<String>,
    /// The tmux session name backing this job, once dispatched.
    #[serde(default)]
    pub tmux_name: Option<String>,
    /// Current lifecycle state.
    #[serde(default)]
    pub state: JobState,
    /// How this job is paused when usage crosses the threshold.
    #[serde(default)]
    pub pause_mode: PauseMode,
    /// Whether this job was launched with `--dangerously-skip-permissions`.
    #[serde(default)]
    pub dangerous: bool,
    /// Model override passed via `--model`, if any.
    #[serde(default)]
    pub model: Option<String>,
    /// Whether the daemon should automatically resume/relaunch this job.
    #[serde(default = "default_true")]
    pub auto_resume: bool,
    /// Epoch ms when this job was created.
    #[serde(default)]
    pub created_at_ms: i64,
    /// Epoch ms of the last state change.
    #[serde(default)]
    pub updated_at_ms: i64,
    /// Epoch ms when the job entered `Paused`, if applicable.
    #[serde(default)]
    pub paused_at_ms: Option<i64>,
    /// Epoch ms after which a fresh sample may resume this job regardless of percentage.
    #[serde(default)]
    pub resume_after_ms: Option<i64>,
    /// Last error message recorded against this job, if any.
    #[serde(default)]
    pub last_error: Option<String>,
    /// Consecutive failed (re)start attempts.
    #[serde(default)]
    pub attempts: u32,
    /// Ring buffer of the most recent state transitions, capped at 20.
    #[serde(default)]
    pub history: Vec<JobEvent>,
}

/// Serde default helper that returns `true`.
fn default_true() -> bool {
    true
}

impl Job {
    /// Transition to a new state, recording the change in `history` (capped
    /// at the most recent 20 events) and updating `updated_at_ms`. Resets
    /// `attempts` to 0 when entering `Running`.
    pub fn transition(&mut self, to: JobState, reason: impl Into<String>, now_ms: i64) {
        let event = JobEvent {
            at_ms: now_ms,
            from: self.state,
            to,
            reason: reason.into(),
        };
        self.state = to;
        self.updated_at_ms = now_ms;
        self.history.push(event);
        let len = self.history.len();
        if len > 20 {
            self.history.drain(0..len - 20);
        }
        if to == JobState::Running {
            self.attempts = 0;
        }
    }
}

/// Top-level persisted collection of jobs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Schedule {
    /// Schema version, for future migrations.
    #[serde(default = "default_version")]
    pub version: u32,
    /// All known jobs, in no particular order.
    #[serde(default)]
    pub jobs: Vec<Job>,
}

/// Serde default helper for `Schedule::version`.
fn default_version() -> u32 {
    1
}

impl Default for Schedule {
    fn default() -> Self {
        Self {
            version: default_version(),
            jobs: Vec::new(),
        }
    }
}

impl Schedule {
    /// Find a job by id.
    pub fn find(&self, id: &str) -> Option<&Job> {
        self.jobs.iter().find(|j| j.id == id)
    }

    /// Find a job by id, mutably.
    pub fn find_mut(&mut self, id: &str) -> Option<&mut Job> {
        self.jobs.iter_mut().find(|j| j.id == id)
    }
}

/// Canonicalize a working directory path for storage. Falls back to the
/// input string unchanged if canonicalization fails (e.g. the path doesn't
/// exist yet). This matters because Claude's project directory encoding is
/// derived from the canonical path: on macOS `/tmp/x` canonicalizes to
/// `/private/tmp/x`, and a probe confirmed a session started in
/// `/tmp/ccsm-probe` landed in `~/.claude/projects/-private-tmp-ccsm-probe/`.
pub fn canonical_cwd(path: &str) -> String {
    std::fs::canonicalize(path)
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| path.to_string())
}

/// Best-effort discovery of the Claude session id for a job that was adopted
/// from an already-running tmux session rather than started by us. Lists
/// `*.jsonl` files under `~/.claude/projects/<encoded cwd>/` with mtime at or
/// after `since_ms - 5000`. Returns the file stem (the session id) only when
/// exactly one file matches; returns `None` when there is no match or more
/// than one equally-plausible candidate.
pub fn discover_session_id(cwd: &str, since_ms: i64) -> Option<String> {
    let home = dirs::home_dir()?;
    let canonical = canonical_cwd(cwd);
    let dir_name = crate::data::io::project_to_dir_name(&canonical);
    let dir = home.join(".claude").join("projects").join(dir_name);
    let cutoff_ms = since_ms - 5000;

    let mut candidates: Vec<(i64, String)> = std::fs::read_dir(&dir)
        .ok()?
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("jsonl") {
                return None;
            }
            // Match on when the session STARTED, not its mtime. A long-running
            // unrelated session in the same directory is written to constantly,
            // so an mtime filter happily matches it, and binding to it would
            // later make `--resume` continue the wrong conversation.
            let (started_ms, entry_cwd) = session_start(&path)?;
            if started_ms < cutoff_ms {
                return None;
            }
            // Corroborate the working directory when the entry records one.
            if let Some(entry_cwd) = entry_cwd {
                if canonical_cwd(&entry_cwd) != canonical {
                    return None;
                }
            }
            let stem = path.file_stem()?.to_str()?.to_string();
            Some((started_ms, stem))
        })
        .collect();

    candidates.sort_by(|a, b| b.0.cmp(&a.0));

    // Anything other than a single unambiguous match means we do not know, and
    // guessing risks resuming somebody else's conversation.
    match candidates.len() {
        1 => Some(candidates.remove(0).1),
        _ => None,
    }
}

/// Read a session JSONL's first line and return `(start_epoch_ms, cwd)`.
/// Only the first line is read, since these files reach many megabytes.
fn session_start(path: &std::path::Path) -> Option<(i64, Option<String>)> {
    use std::io::BufRead;
    let file = std::fs::File::open(path).ok()?;
    let mut first = String::new();
    std::io::BufReader::new(file).read_line(&mut first).ok()?;
    let value: serde_json::Value = serde_json::from_str(first.trim()).ok()?;
    let timestamp = value.get("timestamp")?.as_str()?;
    let started_ms = chrono::DateTime::parse_from_rfc3339(timestamp)
        .ok()?
        .timestamp_millis();
    let cwd = value
        .get("cwd")
        .and_then(|c| c.as_str())
        .map(|c| c.to_string());
    Some((started_ms, cwd))
}
